codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: 60%
        threshold: 20%
