repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: end-of-file-fixer
        - id: check-added-large-files
        - id: check-merge-conflict
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.16.0
      hooks:
      - id: ruff-check
        args: [--fix, --show-fixes, --output-format, grouped]
      - id: ruff-format
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.11.32
      hooks:
        # Ensure uv.lock is up-to-date if pyproject.toml has changed
        - id: uv-lock
