name: odc-stac
channels:
  - conda-forge

dependencies:
  - python =3.10
  - pip

  # odc-stac dependencies
  - odc-geo >=0.3.2
  - rasterio >=1.3.9
  - pystac >=1.9.0 # more flexible handling of extension versions
  - toolz
  - xarray
  # for reading with rasterio from s3
  - boto3

  # planetary-computer lib for URL signing
  - planetary-computer
  - pystac-client

  # JupyterLab
  - jupytext
  - jupyter-server-proxy
  - ipykernel
  - matplotlib-base
  - ipympl
  - dask

  # Some Geo libs
  - geopandas
  - folium

  # conveniences
  - autopep8
  - black
  - isort
  - python-dotenv # for notebooks
  - jupyterlab_code_formatter

  - pip:
      # odc-stac local checkout
      - -e ../
