#!/bin/bash

# This runs when binder is launched

# Replace DASK_DASHBOARD_URL with the proxy location
#sed -i -e "s|DASK_DASHBOARD_URL|${JUPYTERHUB_BASE_URL}user/${JUPYTERHUB_USER}/proxy/8787|g" binder/jupyterlab-workspace.json
# Import the workspace
# jupyter lab workspaces import binder/jupyterlab-workspace.json

date > .startup.log
jupytext -s $HOME/notebooks/*{py,md}

sed -i -e "s|__JUPYTERHUB_USER__|${JUPYTERHUB_USER}|g" $HOME/.config/dask/dask.yaml
sed -i -e "s|__JUPYTERHUB_USER__|${JUPYTERHUB_USER}|g" $HOME/.jupyter/lab/workspaces/demo-*

exec "$@"
