name: Publish odc-stac to PyPI

on:
  workflow_dispatch:

jobs:
  publish-pypi:
    if: |
        github.repository == 'opendatacube/odc-stac'
        && (github.ref == 'refs/heads/stable' || github.ref == 'refs/heads/develop')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Twine
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade \
         toml \
         wheel \
         twine
        python -m pip freeze
    - uses: actions/cache@v2
      id: wheels_cache
      with:
        path: ./wheels
        key: wheels-${{ github.sha }}

    - name: Upload to PyPI
      if: steps.cfg.outputs.publish == 'yes'
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        TWINE_USERNAME: __token__

      run: |
        ls wheels/clean/
        twine upload --non-interactive --skip-existing wheels/clean/*
