name: Publish odc-stac to S3

on:
  workflow_dispatch:

jobs:
  publish-s3:
    if: |
        github.repository == 'opendatacube/odc-stac'
        && github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: wheels_cache
      with:
        path: ./wheels
        key: wheels-${{ github.sha }}

    - name: Prepare for upload to S3
      run: |
        mkdir -p ./pips
        ./scripts/mk-pip-tree.sh ./wheels/dev/ ./pips
        find ./pips -type f
    - name: Upload to S3
      run: |
        echo "Using Keys: ...${AWS_ACCESS_KEY_ID:(-4)}/...${AWS_SECRET_ACCESS_KEY:(-4)}"
        aws s3 ls "${S3_DST}"
        aws s3 sync ./pips/ "${S3_DST}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
        AWS_REGION: 'ap-southeast-2'
        S3_DST: 's3://datacube-core-deployment/'
